### ISSUE TITLE
Not work - Aero 16 XE-5

### ISSUE THREAD

**Issue by techjaw** [Ghioaga/AeroMinimal#4]
help

**Comment by Ghioaga** [comment]
Can you give me a little more information?

**Comment by techjaw** [comment]
Sorry, didn't read enough, I installed the cc ZIP package and everything works now. Thank you for your time and helping us all. Your aeroctl is in version 0.3.0, so I changed it to 0.4.2. I noticed new options that I don't quite know how they work. Can you explain to me?
- GPU boost/oc
- GPU thermal target
- GPU power config (I have inactive here and I don't know why)
- GPU dynamic boost

I noticed that without gcc (and without aeroctl) the number of frames drops a bit, e.g. in cyberpunk (several frames), does your soft also add these frames like gcc?

Honestly, I didn't think you'd respond. But I'm desperately looking for anything because GCC works as it wants, total chaos, sometimes it works sometimes not, sometimes it sets the brightness of the screen and sometimes another. It does not remember the set power plans and in Windows power plans it changes the processor limits to default.
Do you have any way to limit the power of the processor and disable the Nvidia card so that the laptop is silent on power? On the battery, I am able to make the fan not start for 5-6 hours. Total silence. I need power very rarely, only when I play from time to time.

**Comment by Ghioaga** [comment]
Well, I didn't make AeroCtl but as far as I understand, the way Gigabyte made all the controls on their laptops it through WMI ACPI (here is a link with more info https://learn.microsoft.com/en-us/samples/microsoft/windows-driver-samples/wmi-acpi-sample/ ). And with this way of implementing you can look for all the calls that the system can make to the BIOS. Basically you can see all the available options you can change. 
Nitroxis (https://gitlab.com/nitroxis), the guy who made AeroCtl made all the toggles available in this interface. Now because Gigabyte didn't give any documentation ot these options we don't really have any idea what they actually do, as in fully documented and explained way. 
Nitroxis didn't make any kind of installed to his app and recommended to install CC and just kill it and make AeroCtl start by default. But it left some information about these WMI ACPI instructions and how to install them so I found the files from Gigabyte and packed them with AeroCtl. 
So AeroMinimal is just AeroCtl with the WMI ACPI dll. It's a way of running AeroCtl without CC and without letting Gigabyte modify in any way the Windows settings.

About the framerate the only way I see that having or not having CC or AeroCtl can impact performance is about thermals because both apps can manage the fans profile, other than this Windows should manage the performance profiles of the CPU and GPU by itself. The Nvidia Control Panel and Experience can also modify a bit of the GPU performance (and CC didn't interact that much with the GPU anyway.  

Now about your need for silence and battery. while you are on the Laptop's screen if you selected Nvidia Optimus in the BIOS, the laptop will manage when to use and not use the GPU without your intervention (there you can also choose to only use iGPU or dGPU, also you can choose in Nvidia Control Panel). If you use an external Display it will use the dGPU because the way the laptop is wired. This leaves you with managing the CPU and that is also a bit easy and doesn't give you that many options because Windows will manage the CPU and it's freq based on necessity, your laptop being gen12 Windows will use the Efficiency Cores and Performance Cores as it sees fit. 
So overall all that I recommend doing, and how I did it is changing from AeroCtl the fan profile. When I want it silent I choose the Quiet profile that will stop the fans and turn them on when it's really necessary but this will also probably throttle the GPU and CPU. and when I game and want to use the full power I choose the Gaming fan profile that is quite aggressive and the laptop has power limits before thermal limits.

The thing is these laptops are not that well documented and Gigabyte is hurting themselves with the software while the hardware is great. All these I deducted from testing with my laptop so it might not apply to you (it most probably will apply). Another thing is that Gigabyte has some really amateur made software there are basically compilations of apps with a shippy interface. If you want to browse and discover the CC files you can open the install file of CC with 7-zip and just copy whatever you need, from the color profiles for all the different displays to the dlls. If you want to try and discover more and make it a bigger project than I did and improve the community support I'm all down to talk on discord or something. I stopped because I got to a point where I'm comfortable with my laptop. But I'm more than happy to help future and present owners of these great laptops with bad software.

**Comment by techjaw** [comment]
thank you very much for the direction, in aeroctl I only miss the possibility of connecting power profiles from windows to the profile in aeroctl. Now I have to change both aeroctl and PowerPlanSwitcher. Much health and peace
